# Generated by Django 4.1.4 on 2023-01-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
